/*
Copyright 2018 The Kubernetes Authors.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "foremast.ai/foremast/foremast-barrelman/pkg/apis/deployment/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDeploymentMetadatas implements DeploymentMetadataInterface
type FakeDeploymentMetadatas struct {
	Fake *FakeDeploymentV1alpha1
	ns   string
}

var deploymentmetadatasResource = schema.GroupVersionResource{Group: "deployment.foremast.ai", Version: "v1alpha1", Resource: "deploymentmetadatas"}

var deploymentmetadatasKind = schema.GroupVersionKind{Group: "deployment.foremast.ai", Version: "v1alpha1", Kind: "DeploymentMetadata"}

// Get takes name of the deploymentMetadata, and returns the corresponding deploymentMetadata object, and an error if there is any.
func (c *FakeDeploymentMetadatas) Get(name string, options v1.GetOptions) (result *v1alpha1.DeploymentMetadata, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(deploymentmetadatasResource, c.ns, name), &v1alpha1.DeploymentMetadata{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DeploymentMetadata), err
}

// List takes label and field selectors, and returns the list of DeploymentMetadatas that match those selectors.
func (c *FakeDeploymentMetadatas) List(opts v1.ListOptions) (result *v1alpha1.DeploymentMetadataList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(deploymentmetadatasResource, deploymentmetadatasKind, c.ns, opts), &v1alpha1.DeploymentMetadataList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.DeploymentMetadataList{ListMeta: obj.(*v1alpha1.DeploymentMetadataList).ListMeta}
	for _, item := range obj.(*v1alpha1.DeploymentMetadataList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested deploymentMetadatas.
func (c *FakeDeploymentMetadatas) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(deploymentmetadatasResource, c.ns, opts))

}

// Create takes the representation of a deploymentMetadata and creates it.  Returns the server's representation of the deploymentMetadata, and an error, if there is any.
func (c *FakeDeploymentMetadatas) Create(deploymentMetadata *v1alpha1.DeploymentMetadata) (result *v1alpha1.DeploymentMetadata, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(deploymentmetadatasResource, c.ns, deploymentMetadata), &v1alpha1.DeploymentMetadata{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DeploymentMetadata), err
}

// Update takes the representation of a deploymentMetadata and updates it. Returns the server's representation of the deploymentMetadata, and an error, if there is any.
func (c *FakeDeploymentMetadatas) Update(deploymentMetadata *v1alpha1.DeploymentMetadata) (result *v1alpha1.DeploymentMetadata, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(deploymentmetadatasResource, c.ns, deploymentMetadata), &v1alpha1.DeploymentMetadata{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DeploymentMetadata), err
}

// Delete takes name of the deploymentMetadata and deletes it. Returns an error if one occurs.
func (c *FakeDeploymentMetadatas) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(deploymentmetadatasResource, c.ns, name), &v1alpha1.DeploymentMetadata{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDeploymentMetadatas) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(deploymentmetadatasResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.DeploymentMetadataList{})
	return err
}

// Patch applies the patch and returns the patched deploymentMetadata.
func (c *FakeDeploymentMetadatas) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.DeploymentMetadata, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(deploymentmetadatasResource, c.ns, name, data, subresources...), &v1alpha1.DeploymentMetadata{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DeploymentMetadata), err
}
