export const ADD_BASE_METRIC = 'ADD_BASE_METRIC';
export const REQUEST_METRIC_DATA = 'REQUEST_METRIC_DATA';
export const RECEIVE_METRIC_DATA = 'RECEIVE_METRIC_DATA';

export const ADD_ANNOTATION_METRIC = 'ADD_ANNOTATION_METRIC';
export const REQUEST_ANNOTATION_METRIC_DATA = 'REQUEST_ANNOTATION_METRIC_DATA';
export const RECEIVE_ANNOTATION_METRIC_DATA = 'RECEIVE_ANNOTATION_METRIC_DATA';