sudo: required
language: go
go_import_path: foremast.ai/foremast
dist: trusty
matrix:
  include:
  - go: 1.11.1
    env:
    - TESTS=true
    - COVERAGE=true
  - go: 1.11.1
    env:
    - ALL_IN_ONE=true
  - go: 1.11.1
    env:
    - CROSSDOCK=true
  - go: 1.11.1
    env:
    - DOCKER=true
    - DEPLOY=true
  - go: 1.11.1
    env:
    - ES_INTEGRATION_TEST=true
services:
- docker
env:
  global:
  - DOCKER_COMPOSE_VERSION=1.8.0
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: TEhz/1U/+8H+jREQ2aW4cHkLOrKcrXLoQYyoJXssNYJ87JAhHIn+I5wtgBK9P4pb4JyDQ/7h54tq86cH0ka/UP6/VcZSJoiet7S4/cJZrOR04JMHTEm+ljnGfLLumEYLCi0pwqiVJEa/kJ1f8quu+q+83ZbSnVEulY/zxX6WdXRS4m+ANLBjyAz5ryzD4oUIKr572aS/f+tbOtgcXb7OHHO00F4vAE70nyK8V82PKqE6f7lVczqdNQNdSwOxnxzpPhiYKqPcpM96LhPPRWO+0QPHBcok0PJTyYxHzF60guNpT4F61+VG4kxaH5We/CMk1eLuGtabqNSAMS2TqwKQzBsHTCqc59U0w6dhJlU5mWWYnUVm/vCofNgjtJGNvmTjpOYZreB9J1gelLECx6WAfPwDChCWxPdsB1FebqRFGsBNQx0vxgBFqrdgkUDxinLj1sWYMPA/w44UElT4d3k6DCIpv+HK4/6lB4R3ctgBQXvOQgLsuaGlTmclh2vYg0ycN1M75cwXTXcXuLm5KCtqzWLMhCGAxETVSUJ3KRsf+RhwwbLCPB+Mo1TSS4e2lxYhdoXSZ4Q8wPZ0FlWcGvfYAEbZqM+MTorAOdwhRjKRCoJDoqr73TewWStBfRnjqZLvxFJ7YVLla3IR2uvwWggsQ/X9P3TDMyZJN21mildqmT0=
  - secure: t4acmwLdCIdBcHxZ0WBodhcRYeu9dzxH41NXsAiQf6NL/6008xGfsK0eObr2YcWc1+EUHmHzpADpyHsHA63dHvWXu2rJqhcUevajLpm/I9tZaB4xGDFvevHDHzyHJxhgwGZI5kb5RSowUKMuuuvklo+yvRrRQF+7gRJh8aKM7mJ9L/YKX9DwQeUHd7oiB1eB/fbnngFzGp3ubg7t79cqw+G+oGGIoEYsQp3UZmHxI8mJmX3/UdH7EDtzBiTw/2OjuFk49VC9cT5XKAKcCAwkJjK7jtR830mrmrknOIn1QErP88e9pHua0ppdB9jJFe1vpZ6gG+b697Qa4+h6w+5fJ0gEdSAG0QkARp0HnGI4VUKGGDcapTGiIri5lb443SH3N3pKdRjd3zA3UyFCKUlIgICBtDv7tR0VPcRVHNGyO4KEbO6KTeuXFvGKDgmSKSI0sKoGNHYN16nvQDEtpiJPVevT7ltX5eVbdPD51UzSyD0b4TEx/gRwrdEa9PXEmT6XUwh1sx/ZTrOrOGNZ69itOdiGlSxV381XABm0t2ZLb/aLmF8Ns48phcAthfwiOWh2W5n1DSxq1YvySZpmORD4hHtzDffHLeErGaWivNLpoIPzrgs6yzdW231oY/6Gff2mTskoNVvPT+fpT9m+QcvG2UMJs+Trgrsur79kHOJzP/8=
install:
- cd foremast-barrelman
- make
- if [ "$ALL_IN_ONE" == true ]; then docker build . ; fi
- if [ "$DOCKER" == true ]; then docker build . ; fi
- cd ../foremast-service
- bash ./build.sh
- if [ "$ALL_IN_ONE" == true ]; then docker build . ; fi
- if [ "$DOCKER" == true ]; then docker build . ; fi